'use strict';

var constants = require('./constants');

/**
 * Find all contour paths from the crossing data generated by marching squares.
 *
 * @param {Array} pathinfo - Array of path info objects with crossings data
 * @param {Number} xtol - X tolerance for considering points equal (default 0.01)
 * @param {Number} ytol - Y tolerance for considering points equal (default 0.01)
 */
function findAllPaths(pathinfo, xtol, ytol) {
    var cnt, startLoc, i, pi, j;

    // Default tolerance values
    xtol = xtol || 0.01;
    ytol = ytol || 0.01;

    for (i = 0; i < pathinfo.length; i++) {
        pi = pathinfo[i];

        // Process all edge paths (paths that start at the boundary)
        for (j = 0; j < pi.starts.length; j++) {
            startLoc = pi.starts[j];
            makePath(pi, startLoc, 'edge', xtol, ytol);
        }

        // Process all interior paths
        cnt = 0;
        while (Object.keys(pi.crossings).length && cnt < 10000) {
            cnt++;
            startLoc = Object.keys(pi.crossings)[0].split(',').map(Number);
            makePath(pi, startLoc, undefined, xtol, ytol);
        }
        if (cnt === 10000) {
            console.warn('Infinite loop in contour calculation');
        }
    }
}

/**
 * Check if two points are equal within tolerance
 */
function equalPts(pt1, pt2, xtol, ytol) {
    return Math.abs(pt1[0] - pt2[0]) < xtol &&
           Math.abs(pt1[1] - pt2[1]) < ytol;
}

/**
 * Calculate distance in index units between two points
 * Uses the 3rd and 4th items in points (grid indices)
 */
function ptDist(pt1, pt2) {
    var dx = pt1[2] - pt2[2];
    var dy = pt1[3] - pt2[3];
    return Math.sqrt(dx * dx + dy * dy);
}

/**
 * Make a single contour path starting from a given location
 *
 * @param {Object} pi - Path info object for this contour level
 * @param {Array} loc - Starting location [xi, yi]
 * @param {String} edgeflag - 'edge' if this is an edge path, undefined otherwise
 * @param {Number} xtol - X tolerance
 * @param {Number} ytol - Y tolerance
 */
function makePath(pi, loc, edgeflag, xtol, ytol) {
    var locStr = loc.join(',');
    var mi = pi.crossings[locStr];
    var marchStep = getStartStep(mi, edgeflag, loc);

    // Start by going backward a half step and finding the crossing point
    var pts = [getInterpPx(pi, loc, [-marchStep[0], -marchStep[1]])];
    var m = pi.z.length;
    var n = pi.z[0].length;
    var startLoc = loc.slice();
    var startStep = marchStep.slice();
    var cnt;

    // Now follow the path
    for (cnt = 0; cnt < 10000; cnt++) {
        if (mi > 20) {
            mi = constants.CHOOSESADDLE[mi][(marchStep[0] || marchStep[1]) < 0 ? 0 : 1];
            pi.crossings[locStr] = constants.SADDLEREMAINDER[mi];
        } else {
            delete pi.crossings[locStr];
        }

        marchStep = constants.NEWDELTA[mi];
        if (!marchStep) {
            console.warn('Found bad marching index:', mi, loc, pi.level);
            break;
        }

        // Find the crossing a half step forward, then take the full step
        pts.push(getInterpPx(pi, loc, marchStep));
        loc[0] += marchStep[0];
        loc[1] += marchStep[1];
        locStr = loc.join(',');

        // Don't include the same point multiple times
        if (equalPts(pts[pts.length - 1], pts[pts.length - 2], xtol, ytol)) {
            pts.pop();
        }

        var atEdge = (marchStep[0] && (loc[0] < 0 || loc[0] > n - 2)) ||
                (marchStep[1] && (loc[1] < 0 || loc[1] > m - 2));

        var closedLoop = loc[0] === startLoc[0] && loc[1] === startLoc[1] &&
                marchStep[0] === startStep[0] && marchStep[1] === startStep[1];

        // Have we completed a loop, or reached an edge?
        if (closedLoop || (edgeflag && atEdge)) break;

        mi = pi.crossings[locStr];
    }

    if (cnt === 10000) {
        console.warn('Infinite loop in contour path');
    }

    var closedpath = equalPts(pts[0], pts[pts.length - 1], xtol, ytol);

    // Simplify path by removing points that are too close together
    var simplifiedPts = simplifyPath(pts, pi.smoothing, closedpath);

    // Remove index parts (3rd and 4th items) before storing
    for (cnt = 0; cnt < simplifiedPts.length; cnt++) {
        simplifiedPts[cnt].length = 2;
    }

    // Don't return single-point paths
    if (simplifiedPts.length < 2) return;

    if (closedpath) {
        pi.paths.push(simplifiedPts);
    } else {
        // Edge path - merge with existing edge paths if possible
        mergeEdgePath(pi, simplifiedPts, xtol, ytol);
    }
}

/**
 * Simplify path by removing points that are too close together
 */
function simplifyPath(pts, smoothing, closedpath) {
    var totaldist = 0;
    var alldists = [];
    var cnt;

    // Calculate all distances
    for (cnt = 1; cnt < pts.length; cnt++) {
        var thisdist = ptDist(pts[cnt], pts[cnt - 1]);
        totaldist += thisdist;
        alldists.push(thisdist);
    }

    if (alldists.length === 0) return pts;

    var distThresholdFactor = 0.2 * smoothing;
    var distThreshold = totaldist / alldists.length * distThresholdFactor;

    var result = [];
    var cropstart = 0;
    var i, cnt2, cnt3, newpt, ptavg, distgroup;

    function getpt(i) { return pts[i % pts.length]; }

    for (cnt = pts.length - 2; cnt >= cropstart; cnt--) {
        distgroup = alldists[cnt];
        if (distgroup < distThreshold) {
            cnt3 = 0;
            for (cnt2 = cnt - 1; cnt2 >= cropstart; cnt2--) {
                if (distgroup + alldists[cnt2] < distThreshold) {
                    distgroup += alldists[cnt2];
                } else break;
            }

            // Closed path with close points wrapping around the boundary?
            if (closedpath && cnt === pts.length - 2) {
                for (cnt3 = 0; cnt3 < cnt2; cnt3++) {
                    if (distgroup + alldists[cnt3] < distThreshold) {
                        distgroup += alldists[cnt3];
                    } else break;
                }
            }

            var ptcnt = cnt - cnt2 + cnt3 + 1;
            ptavg = Math.floor((cnt + cnt2 + cnt3 + 2) / 2);

            // Keep endpoints for open paths
            if (!closedpath && cnt === pts.length - 2) {
                newpt = pts[pts.length - 1];
            } else if (!closedpath && cnt2 === -1) {
                newpt = pts[0];
            } else if (ptcnt % 2) {
                // Odd number of points - take the central one
                newpt = getpt(ptavg);
            } else {
                // Even number of points - average central two
                newpt = [
                    (getpt(ptavg)[0] + getpt(ptavg + 1)[0]) / 2,
                    (getpt(ptavg)[1] + getpt(ptavg + 1)[1]) / 2,
                    getpt(ptavg)[2],
                    getpt(ptavg)[3]
                ];
            }

            pts.splice(cnt2 + 1, cnt - cnt2 + 1, newpt);
            cnt = cnt2 + 1;
            if (cnt3) cropstart = cnt3;
            if (closedpath) {
                if (cnt === pts.length - 2) pts[cnt3] = pts[pts.length - 1];
                else if (cnt === 0) pts[pts.length - 1] = pts[0];
            }
        }
    }

    pts.splice(0, cropstart);
    return pts;
}

/**
 * Merge an edge path with existing edge paths if they connect
 */
function mergeEdgePath(pi, pts, xtol, ytol) {
    var merged = false;
    var i, j, edgepathi, edgepathj;

    // Try to connect the end of pts to the start of an existing path
    for (i = 0; i < pi.edgepaths.length; i++) {
        edgepathi = pi.edgepaths[i];
        if (!merged && equalPts(edgepathi[0], pts[pts.length - 1], xtol, ytol)) {
            pts.pop();
            merged = true;

            // Check if it ALSO meets the end of another (or the same) path
            var doublemerged = false;
            for (j = 0; j < pi.edgepaths.length; j++) {
                edgepathj = pi.edgepaths[j];
                if (equalPts(edgepathj[edgepathj.length - 1], pts[0], xtol, ytol)) {
                    doublemerged = true;
                    pts.shift();
                    pi.edgepaths.splice(i, 1);
                    if (j === i) {
                        // The path is now closed
                        pi.paths.push(pts.concat(edgepathj));
                    } else {
                        if (j > i) j--;
                        pi.edgepaths[j] = edgepathj.concat(pts, edgepathi);
                    }
                    break;
                }
            }
            if (!doublemerged) {
                pi.edgepaths[i] = pts.concat(edgepathi);
            }
        }
    }

    // Try to connect the start of pts to the end of an existing path
    for (i = 0; i < pi.edgepaths.length; i++) {
        if (merged) break;
        edgepathi = pi.edgepaths[i];
        if (equalPts(edgepathi[edgepathi.length - 1], pts[0], xtol, ytol)) {
            pts.shift();
            pi.edgepaths[i] = edgepathi.concat(pts);
            merged = true;
        }
    }

    if (!merged) {
        pi.edgepaths.push(pts);
    }
}

/**
 * Get the marching step for the first point in the path
 */
function getStartStep(mi, edgeflag, loc) {
    var dx = 0;
    var dy = 0;

    if (mi > 20 && edgeflag) {
        // Saddles start at +/- x
        if (mi === 208 || mi === 1114) {
            dx = loc[0] === 0 ? 1 : -1;
        } else {
            dy = loc[1] === 0 ? 1 : -1;
        }
    } else if (constants.BOTTOMSTART.indexOf(mi) !== -1) {
        dy = 1;
    } else if (constants.LEFTSTART.indexOf(mi) !== -1) {
        dx = 1;
    } else if (constants.TOPSTART.indexOf(mi) !== -1) {
        dy = -1;
    } else {
        dx = -1;
    }
    return [dx, dy];
}

/**
 * Find the pixel coordinates of a particular crossing
 *
 * @param {Object} pi - Path info object at this level
 * @param {Array} loc - Grid index [x, y] of the crossing
 * @param {Array} step - Direction [dx, dy] we're moving on the grid
 * @returns {Array} [xpx, ypx, xi, yi] - pixel location + interpolated grid indices
 */
function getInterpPx(pi, loc, step) {
    var locx = loc[0] + Math.max(step[0], 0);
    var locy = loc[1] + Math.max(step[1], 0);
    var zxy = pi.z[locy][locx];

    // This is a simplified version that works in grid index space
    // For proper pixel coordinates, you'll need to provide scale functions
    if (step[1]) {
        // Vertical interpolation
        var dx = (pi.level - zxy) / (pi.z[locy][locx + 1] - zxy);
        return [
            locx + dx,
            locy,
            locx + dx,
            locy
        ];
    } else {
        // Horizontal interpolation
        var dy = (pi.level - zxy) / (pi.z[locy + 1][locx] - zxy);
        return [
            locx,
            locy + dy,
            locx,
            locy + dy
        ];
    }
}

module.exports = {
    findAllPaths: findAllPaths,
    getInterpPx: getInterpPx
};
